### PR TITLE
Added 2.2.130 attributes

### PR DESCRIPTION
**Pull request by gheuschkel**

### CODE REVIEW

**Comment by glensc** [comment]
merged, @gregsymons should upload new gem version

**Comment by irvingpop** [comment]
awesome!  Thanks for the RHEL 7.2 support. please let me know when this is up on rubygems and I'll update the lvm cookbook to pull in the newer gem.

**Comment by galley123** [comment]
Our team is waiting anxiously for the official version of the gem to be released do we have an ETA of when the gem will be released.

**Comment by SchwarzM** [comment]
+1 waiting for this to make it to LVM cookbook

**Pull request merged**
