### PR TITLE
Lvm 2.02.115 fix

### PR DESCRIPTION
**Pull request by lopaka**

### CODE REVIEW

**Comment by lopaka** [comment]
Fixes #22

**Comment by CFields651** [comment]
I was about to submit a pull request with the same changes.  I tested this code on multiple RHEL7.1 instances at LVM version 2.02.115 and it fixes the issue #22.

**Comment by gregsymons** [comment]
LGTM. I'll try to get this released by the end of the week.

**Comment by jmccann** [comment]
Don't mean to be a pest ... do you have an ETA on when this could be released as a new gem version?

**Comment by gregsymons** [comment]
I'm sorry it's taken so long... I'll try to get to it tonight if I can.

On Thu, Apr 23, 2015 at 9:43 AM, Jacob McCann <notifications@github.com>
wrote:

> Don't mean to be a pest ... do you have an ETA on when this could be
> released as a new gem version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gregsymons/di-ruby-lvm-attrib/pull/23#issuecomment-95609381>
> .
>



-- 
Greg Symons

**Comment by jmccann** [comment]
Thanks!

**Comment by gregsymons** [comment]
Finally, released and pushed to rubygems.

**Pull request merged**
