### PR TITLE
Move 2.02.133(2) attributes

### PR DESCRIPTION
**Pull request by ChiefAlexander**

### CODE REVIEW

**Comment by ChiefAlexander** [comment]
@gregsymons

**Comment by glensc** [comment]
looks like #45 was done incorrectly and my mistake that didn't check the path

i wonder could travis-ci check be made to validate such PRs...

**Comment by ChiefAlexander** [comment]
@glensc I am wondering if we could have this done via a bot instead to remove human error.

**Comment by glensc** [comment]
there is script to run that automates the generation. it's written in README.md

or you mean automatically send PR for each LVM2 tag appeared in LVM2 repository?

**Comment by ChiefAlexander** [comment]
automatically send PR for each LVM2 tag appeared in LVM2 repository. We could also make that check to see if a version of lvm2 is being taken in common os's to see when to release. For example this attribute is needed for ubuntu 16.04

**Comment by glensc** [comment]
looks like the README.md wasn't really clear to use the script, and it has still way too many manual steps. created #47

**Comment by glensc** [comment]
also, sending PR for each LVM2 may be too much, better only add tags that people request, i.e being used in some major OS. but first step could be at least automate creating the patch more automatically than it is now.

**Comment by ChiefAlexander** [comment]
Yeah thats fine. It would be simple to create a bot that checks major OS's but it is just a thought. I agree that a PR for all of the attributes might be a little much.

**Comment by glensc** [comment]
it isn't extremely too much actually:

```
➔ ls 2.02.* -d|wc -l
71
➔ ls -l lib/lvm/attributes|wc -l
32
```

first `ls` is all 2.02 releases from LVM2 repository, second `ls` is lvm versions already present in this repository.

**Comment by glensc** [comment]
also, how would you write that bot? have you written something like that before? do you have examples?

i would finish #47 so the bot just has to run `./update-lvm.sh` script, push the branch, make PR, keep track of PR's it already has made (or just check some other means what versions not to create PR for)

**Comment by ChiefAlexander** [comment]
I would setup a coordinator service to just run the check and make a pr (most experience with rundeck and jenkins), using some ruby script to autocheck. The only examples that I would have are internal to my company. If you would like I can take some time this weekend and give it a go.

**Comment by glensc** [comment]
#47 is ready, subscribe there or just have look. seems working for me.

**Pull request merged**
