### PR TITLE
use git tag -l to list tags

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by gregsymons** [comment]
LGTM.

**Comment by gregsymons** [comment]
Released in v0.0.20

**Comment by glensc** [comment]
btw, this was ok in initial submission (dd7e5388cc0b7d1833ed4cb718f64fc5df67bd28), but somewhy @lopaka changed it to `git tags` to `git tag` in (efa707830b4520e67ce6acd2f47c50bb0b8d3035)

**Comment by gregsymons** [comment]
Hmmm... I'll try to keep a closer eye on changes to that script from now on. I wonder if it was maybe a difference in git versions?

**Comment by gregsymons** [comment]
Or maybe you had an alias for `git tags` and forgot that it was an alias, not a built-in command when you wrote the script.

**Comment by glensc** [comment]
indeed, i have `git tags` alias, did not even remember i added it :)

**Pull request merged**
