### PR TITLE
Added v2_02_166 attributes

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by tas50** [comment]
@gregsymons Any chance we can get this merged and released?

**Comment by ironmike-au** [comment]
Thanks for merging this in! Any chance the release of (I presume) 0.0.28 can happen soon? This is also breaking RHEL 7.3. Thanks!

**Comment by glensc** [comment]
only @gregsymons can publish this gem. i've prepared #50 so it could be done automatically in the future on git tag by travis-ci.

**Comment by afdezl** [comment]
Indeed, breaking RHEL 7.2 as well. Hopefully 0.0.28 fixes it.

**Comment by ironmike-au** [comment]
@afdezl - I created a fork temporarily with the fix in it. I'm using it with the LVM cookbook in Chef with success, but only until the real gem is fixed. You can find the two gems over here: https://rubygems.org/profiles/otakumike. Hope it helps!

**Comment by afdezl** [comment]
@otakumike Thanks for pointing me to this. Any idea of when the real gem will be released? @gregsymons

**Comment by ryankoski-at-target** [comment]
Add us to the list of folks waiting for this merge. Much appreciated! @gregsymons

**Pull request merged**
