### PR TITLE
Added 2.02.119 attributes

### PR DESCRIPTION
**Pull request by glensc**
Generated similarly to #26

### CODE REVIEW

**Comment by glensc** [comment]
ping?

**Comment by gregsymons** [comment]
Sorry... was a bit swamped at work. I'll try to get this out by the end of the week. BTW, since you're obviously doing more work on this than I am, do you want commit privileges?

**Comment by glensc** [comment]
well. i just run the script, i don't know how to verify are the changes okay. and then again, users can report back if the changes are not okay i guess :) besides you would still do the gem upload and can verify then yourself.

you can give, maybe i can help out with some other bits and bolts :)

**Comment by gregsymons** [comment]
Heh. I don't actually verify the changes are OK, I'm trusting the script and relying on the users to report back bugs. I think eventually, it would be better to dynamically generate the bindings at install time, since the gem is starting to get a little big with all these different attribute binding files. But the problem comes from the missing attribute type case. Though I suppose we could automate generating the type conversion map, too.

Anyway, I'm going to merge this in, as I don't see anything hinky going on.

**Comment by glensc** [comment]
that is basically how i do in [pld linux](https://github.com/pld-linux/ruby-di-ruby-lvm-attrib) rpm packaging.

i include only attributes for current lvm2 version, and package itself has strict dependency on lvm2 version, so you can't upgrade lvm2 without having new version of ruby-lvm-attrib package as well

```
$ rpm -qpl ruby-di-ruby-lvm-attrib-0.0.19-2.noarch.rpm
/usr/share/gems/specifications/di-ruby-lvm-attrib-0.0.19.gemspec
/usr/share/ruby/vendor_ruby/lvm
/usr/share/ruby/vendor_ruby/lvm/attributes
/usr/share/ruby/vendor_ruby/lvm/attributes.rb
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)/lvs.yaml
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)/lvsseg.yaml
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)/pvs.yaml
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)/pvsseg.yaml
/usr/share/ruby/vendor_ruby/lvm/attributes/2.02.114(2)/vgs.yaml
```

**Comment by gregsymons** [comment]
Released in v0.0.21 and pushed to rubygems.

**Pull request merged**
