### PR TITLE
If unable to load lvm attributes give proper error message. Fixes #19

### LINKED ISSUE #19: If lvm version not supported give error message
We recently ran into an issue where we were using an older version of this gem with a newer version of lvm that was not supported yet and saw this error message,

    Errno::ENOENT: No such file or directory - /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/di-ruby-lvm-attrib-0.0.14/lib/lvm/attributes/2.02.111(2)/lvs.yaml
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `initialize'
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `open'
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `load_file'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/di-ruby-lvm-attrib-0.0.14/lib/lvm/attributes.rb:20:in `load'

It would be great if this exception was caught and re-thrown with an error message saying that this version of LVM is not supported yet.

### PR DESCRIPTION
**Pull request by bbaugher**

### CODE REVIEW

**Comment by gregsymons** [comment]
:+1: LGTM

**Comment by gregsymons** [comment]
I don't know if you noticed, but DI has transferred the di-ruby-lvm* gems to my control. I'll try to get this merged and released sometime either today or tomorrow.

**Comment by bbaugher** [comment]
Great thanks!

**Comment by gregsymons** [comment]
Sorry for the delay in getting this out... just started a new job, and things have been hectic. Since there's now another pull request for adding new attributes, I'll definitely prioritize getting both of these out by the end of the week.

**Comment by gregsymons** [comment]
Version 0.0.17 has been released and pushed to rubygems.

**Pull request merged**
